// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/ephemeris.proto

package com.google.location.custom_suplclient.supl;

public final class Ephemeris {
  private Ephemeris() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GpsTimeProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gnss.GpsTimeProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 nanosecond = 1;</code>
     * @return Whether the nanosecond field is set.
     */
    boolean hasNanosecond();
    /**
     * <code>optional int64 nanosecond = 1;</code>
     * @return The nanosecond.
     */
    long getNanosecond();
  }
  /**
   * Protobuf type {@code gnss.GpsTimeProto}
   */
  public static final class GpsTimeProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gnss.GpsTimeProto)
      GpsTimeProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GpsTimeProto.newBuilder() to construct.
    private GpsTimeProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GpsTimeProto() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GpsTimeProto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GpsTimeProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              nanosecond_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.location.custom_suplclient.supl.Ephemeris.internal_static_gnss_GpsTimeProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.location.custom_suplclient.supl.Ephemeris.internal_static_gnss_GpsTimeProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto.class, com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto.Builder.class);
    }

    private int bitField0_;
    public static final int NANOSECOND_FIELD_NUMBER = 1;
    private long nanosecond_;
    /**
     * <code>optional int64 nanosecond = 1;</code>
     * @return Whether the nanosecond field is set.
     */
    @java.lang.Override
    public boolean hasNanosecond() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int64 nanosecond = 1;</code>
     * @return The nanosecond.
     */
    @java.lang.Override
    public long getNanosecond() {
      return nanosecond_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, nanosecond_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, nanosecond_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto)) {
        return super.equals(obj);
      }
      com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto other = (com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto) obj;

      if (hasNanosecond() != other.hasNanosecond()) return false;
      if (hasNanosecond()) {
        if (getNanosecond()
            != other.getNanosecond()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasNanosecond()) {
        hash = (37 * hash) + NANOSECOND_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getNanosecond());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gnss.GpsTimeProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gnss.GpsTimeProto)
        com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.location.custom_suplclient.supl.Ephemeris.internal_static_gnss_GpsTimeProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.location.custom_suplclient.supl.Ephemeris.internal_static_gnss_GpsTimeProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto.class, com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto.Builder.class);
      }

      // Construct using com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nanosecond_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.location.custom_suplclient.supl.Ephemeris.internal_static_gnss_GpsTimeProto_descriptor;
      }

      @java.lang.Override
      public com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto getDefaultInstanceForType() {
        return com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto build() {
        com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto buildPartial() {
        com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto result = new com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.nanosecond_ = nanosecond_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto) {
          return mergeFrom((com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto other) {
        if (other == com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto.getDefaultInstance()) return this;
        if (other.hasNanosecond()) {
          setNanosecond(other.getNanosecond());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long nanosecond_ ;
      /**
       * <code>optional int64 nanosecond = 1;</code>
       * @return Whether the nanosecond field is set.
       */
      @java.lang.Override
      public boolean hasNanosecond() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int64 nanosecond = 1;</code>
       * @return The nanosecond.
       */
      @java.lang.Override
      public long getNanosecond() {
        return nanosecond_;
      }
      /**
       * <code>optional int64 nanosecond = 1;</code>
       * @param value The nanosecond to set.
       * @return This builder for chaining.
       */
      public Builder setNanosecond(long value) {
        bitField0_ |= 0x00000001;
        nanosecond_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 nanosecond = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNanosecond() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nanosecond_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gnss.GpsTimeProto)
    }

    // @@protoc_insertion_point(class_scope:gnss.GpsTimeProto)
    private static final com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto();
    }

    public static com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<GpsTimeProto>
        PARSER = new com.google.protobuf.AbstractParser<GpsTimeProto>() {
      @java.lang.Override
      public GpsTimeProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GpsTimeProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GpsTimeProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GpsTimeProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.location.custom_suplclient.supl.Ephemeris.GpsTimeProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gnss_GpsTimeProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gnss_GpsTimeProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036src/main/proto/ephemeris.proto\022\004gnss\"\"" +
      "\n\014GpsTimeProto\022\022\n\nnanosecond\030\001 \001(\003B/\n*co" +
      "m.google.location.custom_suplclient.supl" +
      "\200\001\000"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_gnss_GpsTimeProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gnss_GpsTimeProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gnss_GpsTimeProto_descriptor,
        new java.lang.String[] { "Nanosecond", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
