// Generated by the protocol buffer compiler.  DO NOT EDIT!

package android.location.cts.nano;

@SuppressWarnings("hiding")
public interface Ephemeris {

  public static final class GpsTimeProto extends
      com.google.protobuf.nano.MessageNano {

    private static volatile GpsTimeProto[] _emptyArray;
    public static GpsTimeProto[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new GpsTimeProto[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int64 nanosecond = 1;
    public long nanosecond;

    public GpsTimeProto() {
      clear();
    }

    public GpsTimeProto clear() {
      nanosecond = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.nanosecond != 0L) {
        output.writeInt64(1, this.nanosecond);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.nanosecond != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, this.nanosecond);
      }
      return size;
    }

    @Override
    public GpsTimeProto mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.nanosecond = input.readInt64();
            break;
          }
        }
      }
    }

    public static GpsTimeProto parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new GpsTimeProto(), data);
    }

    public static GpsTimeProto parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new GpsTimeProto().mergeFrom(input);
    }
  }

  public static final class GpsEphemerisProto extends
      com.google.protobuf.nano.MessageNano {

    private static volatile GpsEphemerisProto[] _emptyArray;
    public static GpsEphemerisProto[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new GpsEphemerisProto[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .android.location.cts.GpsTimeProto data_time = 1;
    public android.location.cts.nano.Ephemeris.GpsTimeProto dataTime;

    // optional int32 prn = 2;
    public int prn;

    // optional int32 week = 3;
    public int week;

    // optional int32 l2_code = 4;
    public int l2Code;

    // optional int32 l2_flag = 5;
    public int l2Flag;

    // optional double sv_accuracy_m = 6;
    public double svAccuracyM;

    // optional int32 sv_health = 7;
    public int svHealth;

    // optional int32 iode = 8;
    public int iode;

    // optional int32 iodc = 9;
    public int iodc;

    // optional double toc = 10;
    public double toc;

    // optional double toe = 11;
    public double toe;

    // optional double tom = 12;
    public double tom;

    // optional double af0 = 13;
    public double af0;

    // optional double af1 = 14;
    public double af1;

    // optional double af2 = 15;
    public double af2;

    // optional double tgd = 16;
    public double tgd;

    // optional double root_of_a = 17;
    public double rootOfA;

    // optional double e = 18;
    public double e;

    // optional double i_0 = 19;
    public double i0;

    // optional double i_dot = 20;
    public double iDot;

    // optional double omega = 21;
    public double omega;

    // optional double omega_0 = 22;
    public double omega0;

    // optional double omega_dot = 23;
    public double omegaDot;

    // optional double m_0 = 24;
    public double m0;

    // optional double delta_n = 25;
    public double deltaN;

    // optional double crc = 26;
    public double crc;

    // optional double crs = 27;
    public double crs;

    // optional double cuc = 28;
    public double cuc;

    // optional double cus = 29;
    public double cus;

    // optional double cic = 30;
    public double cic;

    // optional double cis = 31;
    public double cis;

    // optional double fit_interval = 32;
    public double fitInterval;

    public GpsEphemerisProto() {
      clear();
    }

    public GpsEphemerisProto clear() {
      dataTime = null;
      prn = 0;
      week = 0;
      l2Code = 0;
      l2Flag = 0;
      svAccuracyM = 0D;
      svHealth = 0;
      iode = 0;
      iodc = 0;
      toc = 0D;
      toe = 0D;
      tom = 0D;
      af0 = 0D;
      af1 = 0D;
      af2 = 0D;
      tgd = 0D;
      rootOfA = 0D;
      e = 0D;
      i0 = 0D;
      iDot = 0D;
      omega = 0D;
      omega0 = 0D;
      omegaDot = 0D;
      m0 = 0D;
      deltaN = 0D;
      crc = 0D;
      crs = 0D;
      cuc = 0D;
      cus = 0D;
      cic = 0D;
      cis = 0D;
      fitInterval = 0D;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.dataTime != null) {
        output.writeMessage(1, this.dataTime);
      }
      if (this.prn != 0) {
        output.writeInt32(2, this.prn);
      }
      if (this.week != 0) {
        output.writeInt32(3, this.week);
      }
      if (this.l2Code != 0) {
        output.writeInt32(4, this.l2Code);
      }
      if (this.l2Flag != 0) {
        output.writeInt32(5, this.l2Flag);
      }
      if (java.lang.Double.doubleToLongBits(this.svAccuracyM)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(6, this.svAccuracyM);
      }
      if (this.svHealth != 0) {
        output.writeInt32(7, this.svHealth);
      }
      if (this.iode != 0) {
        output.writeInt32(8, this.iode);
      }
      if (this.iodc != 0) {
        output.writeInt32(9, this.iodc);
      }
      if (java.lang.Double.doubleToLongBits(this.toc)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(10, this.toc);
      }
      if (java.lang.Double.doubleToLongBits(this.toe)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(11, this.toe);
      }
      if (java.lang.Double.doubleToLongBits(this.tom)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(12, this.tom);
      }
      if (java.lang.Double.doubleToLongBits(this.af0)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(13, this.af0);
      }
      if (java.lang.Double.doubleToLongBits(this.af1)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(14, this.af1);
      }
      if (java.lang.Double.doubleToLongBits(this.af2)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(15, this.af2);
      }
      if (java.lang.Double.doubleToLongBits(this.tgd)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(16, this.tgd);
      }
      if (java.lang.Double.doubleToLongBits(this.rootOfA)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(17, this.rootOfA);
      }
      if (java.lang.Double.doubleToLongBits(this.e)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(18, this.e);
      }
      if (java.lang.Double.doubleToLongBits(this.i0)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(19, this.i0);
      }
      if (java.lang.Double.doubleToLongBits(this.iDot)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(20, this.iDot);
      }
      if (java.lang.Double.doubleToLongBits(this.omega)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(21, this.omega);
      }
      if (java.lang.Double.doubleToLongBits(this.omega0)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(22, this.omega0);
      }
      if (java.lang.Double.doubleToLongBits(this.omegaDot)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(23, this.omegaDot);
      }
      if (java.lang.Double.doubleToLongBits(this.m0)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(24, this.m0);
      }
      if (java.lang.Double.doubleToLongBits(this.deltaN)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(25, this.deltaN);
      }
      if (java.lang.Double.doubleToLongBits(this.crc)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(26, this.crc);
      }
      if (java.lang.Double.doubleToLongBits(this.crs)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(27, this.crs);
      }
      if (java.lang.Double.doubleToLongBits(this.cuc)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(28, this.cuc);
      }
      if (java.lang.Double.doubleToLongBits(this.cus)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(29, this.cus);
      }
      if (java.lang.Double.doubleToLongBits(this.cic)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(30, this.cic);
      }
      if (java.lang.Double.doubleToLongBits(this.cis)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(31, this.cis);
      }
      if (java.lang.Double.doubleToLongBits(this.fitInterval)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(32, this.fitInterval);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.dataTime != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.dataTime);
      }
      if (this.prn != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.prn);
      }
      if (this.week != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, this.week);
      }
      if (this.l2Code != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, this.l2Code);
      }
      if (this.l2Flag != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(5, this.l2Flag);
      }
      if (java.lang.Double.doubleToLongBits(this.svAccuracyM)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(6, this.svAccuracyM);
      }
      if (this.svHealth != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(7, this.svHealth);
      }
      if (this.iode != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(8, this.iode);
      }
      if (this.iodc != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(9, this.iodc);
      }
      if (java.lang.Double.doubleToLongBits(this.toc)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(10, this.toc);
      }
      if (java.lang.Double.doubleToLongBits(this.toe)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(11, this.toe);
      }
      if (java.lang.Double.doubleToLongBits(this.tom)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(12, this.tom);
      }
      if (java.lang.Double.doubleToLongBits(this.af0)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(13, this.af0);
      }
      if (java.lang.Double.doubleToLongBits(this.af1)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(14, this.af1);
      }
      if (java.lang.Double.doubleToLongBits(this.af2)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(15, this.af2);
      }
      if (java.lang.Double.doubleToLongBits(this.tgd)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(16, this.tgd);
      }
      if (java.lang.Double.doubleToLongBits(this.rootOfA)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(17, this.rootOfA);
      }
      if (java.lang.Double.doubleToLongBits(this.e)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(18, this.e);
      }
      if (java.lang.Double.doubleToLongBits(this.i0)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(19, this.i0);
      }
      if (java.lang.Double.doubleToLongBits(this.iDot)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(20, this.iDot);
      }
      if (java.lang.Double.doubleToLongBits(this.omega)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(21, this.omega);
      }
      if (java.lang.Double.doubleToLongBits(this.omega0)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(22, this.omega0);
      }
      if (java.lang.Double.doubleToLongBits(this.omegaDot)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(23, this.omegaDot);
      }
      if (java.lang.Double.doubleToLongBits(this.m0)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(24, this.m0);
      }
      if (java.lang.Double.doubleToLongBits(this.deltaN)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(25, this.deltaN);
      }
      if (java.lang.Double.doubleToLongBits(this.crc)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(26, this.crc);
      }
      if (java.lang.Double.doubleToLongBits(this.crs)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(27, this.crs);
      }
      if (java.lang.Double.doubleToLongBits(this.cuc)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(28, this.cuc);
      }
      if (java.lang.Double.doubleToLongBits(this.cus)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(29, this.cus);
      }
      if (java.lang.Double.doubleToLongBits(this.cic)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(30, this.cic);
      }
      if (java.lang.Double.doubleToLongBits(this.cis)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(31, this.cis);
      }
      if (java.lang.Double.doubleToLongBits(this.fitInterval)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(32, this.fitInterval);
      }
      return size;
    }

    @Override
    public GpsEphemerisProto mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.dataTime == null) {
              this.dataTime = new android.location.cts.nano.Ephemeris.GpsTimeProto();
            }
            input.readMessage(this.dataTime);
            break;
          }
          case 16: {
            this.prn = input.readInt32();
            break;
          }
          case 24: {
            this.week = input.readInt32();
            break;
          }
          case 32: {
            this.l2Code = input.readInt32();
            break;
          }
          case 40: {
            this.l2Flag = input.readInt32();
            break;
          }
          case 49: {
            this.svAccuracyM = input.readDouble();
            break;
          }
          case 56: {
            this.svHealth = input.readInt32();
            break;
          }
          case 64: {
            this.iode = input.readInt32();
            break;
          }
          case 72: {
            this.iodc = input.readInt32();
            break;
          }
          case 81: {
            this.toc = input.readDouble();
            break;
          }
          case 89: {
            this.toe = input.readDouble();
            break;
          }
          case 97: {
            this.tom = input.readDouble();
            break;
          }
          case 105: {
            this.af0 = input.readDouble();
            break;
          }
          case 113: {
            this.af1 = input.readDouble();
            break;
          }
          case 121: {
            this.af2 = input.readDouble();
            break;
          }
          case 129: {
            this.tgd = input.readDouble();
            break;
          }
          case 137: {
            this.rootOfA = input.readDouble();
            break;
          }
          case 145: {
            this.e = input.readDouble();
            break;
          }
          case 153: {
            this.i0 = input.readDouble();
            break;
          }
          case 161: {
            this.iDot = input.readDouble();
            break;
          }
          case 169: {
            this.omega = input.readDouble();
            break;
          }
          case 177: {
            this.omega0 = input.readDouble();
            break;
          }
          case 185: {
            this.omegaDot = input.readDouble();
            break;
          }
          case 193: {
            this.m0 = input.readDouble();
            break;
          }
          case 201: {
            this.deltaN = input.readDouble();
            break;
          }
          case 209: {
            this.crc = input.readDouble();
            break;
          }
          case 217: {
            this.crs = input.readDouble();
            break;
          }
          case 225: {
            this.cuc = input.readDouble();
            break;
          }
          case 233: {
            this.cus = input.readDouble();
            break;
          }
          case 241: {
            this.cic = input.readDouble();
            break;
          }
          case 249: {
            this.cis = input.readDouble();
            break;
          }
          case 257: {
            this.fitInterval = input.readDouble();
            break;
          }
        }
      }
    }

    public static GpsEphemerisProto parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new GpsEphemerisProto(), data);
    }

    public static GpsEphemerisProto parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new GpsEphemerisProto().mergeFrom(input);
    }
  }

  public static final class IonosphericModelProto extends
      com.google.protobuf.nano.MessageNano {

    private static volatile IonosphericModelProto[] _emptyArray;
    public static IonosphericModelProto[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new IonosphericModelProto[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .android.location.cts.GpsTimeProto data_time = 1;
    public android.location.cts.nano.Ephemeris.GpsTimeProto dataTime;

    // repeated double alpha = 2;
    public double[] alpha;

    // repeated double beta = 3;
    public double[] beta;

    public IonosphericModelProto() {
      clear();
    }

    public IonosphericModelProto clear() {
      dataTime = null;
      alpha = com.google.protobuf.nano.WireFormatNano.EMPTY_DOUBLE_ARRAY;
      beta = com.google.protobuf.nano.WireFormatNano.EMPTY_DOUBLE_ARRAY;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.dataTime != null) {
        output.writeMessage(1, this.dataTime);
      }
      if (this.alpha != null && this.alpha.length > 0) {
        for (int i = 0; i < this.alpha.length; i++) {
          output.writeDouble(2, this.alpha[i]);
        }
      }
      if (this.beta != null && this.beta.length > 0) {
        for (int i = 0; i < this.beta.length; i++) {
          output.writeDouble(3, this.beta[i]);
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.dataTime != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.dataTime);
      }
      if (this.alpha != null && this.alpha.length > 0) {
        int dataSize = 8 * this.alpha.length;
        size += dataSize;
        size += 1 * this.alpha.length;
      }
      if (this.beta != null && this.beta.length > 0) {
        int dataSize = 8 * this.beta.length;
        size += dataSize;
        size += 1 * this.beta.length;
      }
      return size;
    }

    @Override
    public IonosphericModelProto mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.dataTime == null) {
              this.dataTime = new android.location.cts.nano.Ephemeris.GpsTimeProto();
            }
            input.readMessage(this.dataTime);
            break;
          }
          case 17: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 17);
            int i = this.alpha == null ? 0 : this.alpha.length;
            double[] newArray = new double[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.alpha, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readDouble();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readDouble();
            this.alpha = newArray;
            break;
          }
          case 18: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            int arrayLength = length / 8;
            int i = this.alpha == null ? 0 : this.alpha.length;
            double[] newArray = new double[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.alpha, 0, newArray, 0, i);
            }
            for (; i < newArray.length; i++) {
              newArray[i] = input.readDouble();
            }
            this.alpha = newArray;
            input.popLimit(limit);
            break;
          }
          case 25: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 25);
            int i = this.beta == null ? 0 : this.beta.length;
            double[] newArray = new double[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.beta, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readDouble();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readDouble();
            this.beta = newArray;
            break;
          }
          case 26: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            int arrayLength = length / 8;
            int i = this.beta == null ? 0 : this.beta.length;
            double[] newArray = new double[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.beta, 0, newArray, 0, i);
            }
            for (; i < newArray.length; i++) {
              newArray[i] = input.readDouble();
            }
            this.beta = newArray;
            input.popLimit(limit);
            break;
          }
        }
      }
    }

    public static IonosphericModelProto parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new IonosphericModelProto(), data);
    }

    public static IonosphericModelProto parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new IonosphericModelProto().mergeFrom(input);
    }
  }

  public static final class UtcModelProto extends
      com.google.protobuf.nano.MessageNano {

    private static volatile UtcModelProto[] _emptyArray;
    public static UtcModelProto[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new UtcModelProto[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional double a_0 = 1;
    public double a0;

    // optional double a_1 = 2;
    public double a1;

    // optional int64 tow = 3;
    public long tow;

    // optional int32 leap_seconds = 4;
    public int leapSeconds;

    public UtcModelProto() {
      clear();
    }

    public UtcModelProto clear() {
      a0 = 0D;
      a1 = 0D;
      tow = 0L;
      leapSeconds = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (java.lang.Double.doubleToLongBits(this.a0)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(1, this.a0);
      }
      if (java.lang.Double.doubleToLongBits(this.a1)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(2, this.a1);
      }
      if (this.tow != 0L) {
        output.writeInt64(3, this.tow);
      }
      if (this.leapSeconds != 0) {
        output.writeInt32(4, this.leapSeconds);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (java.lang.Double.doubleToLongBits(this.a0)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(1, this.a0);
      }
      if (java.lang.Double.doubleToLongBits(this.a1)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(2, this.a1);
      }
      if (this.tow != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(3, this.tow);
      }
      if (this.leapSeconds != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, this.leapSeconds);
      }
      return size;
    }

    @Override
    public UtcModelProto mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 9: {
            this.a0 = input.readDouble();
            break;
          }
          case 17: {
            this.a1 = input.readDouble();
            break;
          }
          case 24: {
            this.tow = input.readInt64();
            break;
          }
          case 32: {
            this.leapSeconds = input.readInt32();
            break;
          }
        }
      }
    }

    public static UtcModelProto parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new UtcModelProto(), data);
    }

    public static UtcModelProto parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new UtcModelProto().mergeFrom(input);
    }
  }

  public static final class GpsNavMessageProto extends
      com.google.protobuf.nano.MessageNano {

    // enum RpcStatus
    public static final int UNKNOWN_RPC_STATUS = 0;
    public static final int SUCCESS = 1;
    public static final int SERVER_ERROR = 2;

    private static volatile GpsNavMessageProto[] _emptyArray;
    public static GpsNavMessageProto[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new GpsNavMessageProto[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .android.location.cts.GpsNavMessageProto.RpcStatus rpc_status = 1;
    public int rpcStatus;

    // optional .android.location.cts.IonosphericModelProto iono = 2;
    public android.location.cts.nano.Ephemeris.IonosphericModelProto iono;

    // optional .android.location.cts.UtcModelProto utc_model = 3;
    public android.location.cts.nano.Ephemeris.UtcModelProto utcModel;

    // repeated .android.location.cts.GpsEphemerisProto ephemerids = 4;
    public android.location.cts.nano.Ephemeris.GpsEphemerisProto[] ephemerids;

    public GpsNavMessageProto() {
      clear();
    }

    public GpsNavMessageProto clear() {
      rpcStatus = android.location.cts.nano.Ephemeris.GpsNavMessageProto.UNKNOWN_RPC_STATUS;
      iono = null;
      utcModel = null;
      ephemerids = android.location.cts.nano.Ephemeris.GpsEphemerisProto.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.rpcStatus != android.location.cts.nano.Ephemeris.GpsNavMessageProto.UNKNOWN_RPC_STATUS) {
        output.writeInt32(1, this.rpcStatus);
      }
      if (this.iono != null) {
        output.writeMessage(2, this.iono);
      }
      if (this.utcModel != null) {
        output.writeMessage(3, this.utcModel);
      }
      if (this.ephemerids != null && this.ephemerids.length > 0) {
        for (int i = 0; i < this.ephemerids.length; i++) {
          android.location.cts.nano.Ephemeris.GpsEphemerisProto element = this.ephemerids[i];
          if (element != null) {
            output.writeMessage(4, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.rpcStatus != android.location.cts.nano.Ephemeris.GpsNavMessageProto.UNKNOWN_RPC_STATUS) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, this.rpcStatus);
      }
      if (this.iono != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.iono);
      }
      if (this.utcModel != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3, this.utcModel);
      }
      if (this.ephemerids != null && this.ephemerids.length > 0) {
        for (int i = 0; i < this.ephemerids.length; i++) {
          android.location.cts.nano.Ephemeris.GpsEphemerisProto element = this.ephemerids[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(4, element);
          }
        }
      }
      return size;
    }

    @Override
    public GpsNavMessageProto mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            int value = input.readInt32();
            switch (value) {
              case android.location.cts.nano.Ephemeris.GpsNavMessageProto.UNKNOWN_RPC_STATUS:
              case android.location.cts.nano.Ephemeris.GpsNavMessageProto.SUCCESS:
              case android.location.cts.nano.Ephemeris.GpsNavMessageProto.SERVER_ERROR:
                this.rpcStatus = value;
                break;
            }
            break;
          }
          case 18: {
            if (this.iono == null) {
              this.iono = new android.location.cts.nano.Ephemeris.IonosphericModelProto();
            }
            input.readMessage(this.iono);
            break;
          }
          case 26: {
            if (this.utcModel == null) {
              this.utcModel = new android.location.cts.nano.Ephemeris.UtcModelProto();
            }
            input.readMessage(this.utcModel);
            break;
          }
          case 34: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 34);
            int i = this.ephemerids == null ? 0 : this.ephemerids.length;
            android.location.cts.nano.Ephemeris.GpsEphemerisProto[] newArray =
                new android.location.cts.nano.Ephemeris.GpsEphemerisProto[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.ephemerids, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new android.location.cts.nano.Ephemeris.GpsEphemerisProto();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new android.location.cts.nano.Ephemeris.GpsEphemerisProto();
            input.readMessage(newArray[i]);
            this.ephemerids = newArray;
            break;
          }
        }
      }
    }

    public static GpsNavMessageProto parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new GpsNavMessageProto(), data);
    }

    public static GpsNavMessageProto parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new GpsNavMessageProto().mergeFrom(input);
    }
  }
}
