// Generated by the protocol buffer compiler.  DO NOT EDIT!

package android.location.cts.nano;

@SuppressWarnings("hiding")
public interface GalileoEphemeris {

  public static final class GalTimeProto extends
      com.google.protobuf.nano.MessageNano {

    private static volatile GalTimeProto[] _emptyArray;
    public static GalTimeProto[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new GalTimeProto[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int64 nanosecond = 1;
    public long nanosecond;

    public GalTimeProto() {
      clear();
    }

    public GalTimeProto clear() {
      nanosecond = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.nanosecond != 0L) {
        output.writeInt64(1, this.nanosecond);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.nanosecond != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, this.nanosecond);
      }
      return size;
    }

    @Override
    public GalTimeProto mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.nanosecond = input.readInt64();
            break;
          }
        }
      }
    }

    public static GalTimeProto parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new GalTimeProto(), data);
    }

    public static GalTimeProto parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new GalTimeProto().mergeFrom(input);
    }
  }

  public static final class GalEphemerisProto extends
      com.google.protobuf.nano.MessageNano {

    private static volatile GalEphemerisProto[] _emptyArray;
    public static GalEphemerisProto[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new GalEphemerisProto[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .android.location.cts.GalTimeProto data_time = 1;
    public android.location.cts.nano.GalileoEphemeris.GalTimeProto dataTime;

    // optional int32 prn = 2;
    public int prn;

    // optional int32 week = 3;
    public int week;

    // optional double sv_accuracy_m = 4;
    public double svAccuracyM;

    // optional int32 sv_health = 5;
    public int svHealth;

    // optional int32 iode = 6;
    public int iode;

    // optional int32 iodc = 7;
    public int iodc;

    // optional double toc = 8;
    public double toc;

    // optional double toe = 9;
    public double toe;

    // optional double tom = 10;
    public double tom;

    // optional double af0 = 11;
    public double af0;

    // optional double af1 = 12;
    public double af1;

    // optional double af2 = 13;
    public double af2;

    // optional double tgd = 14;
    public double tgd;

    // optional double root_of_a = 15;
    public double rootOfA;

    // optional double e = 16;
    public double e;

    // optional double i_0 = 17;
    public double i0;

    // optional double i_dot = 18;
    public double iDot;

    // optional double omega = 19;
    public double omega;

    // optional double omega_0 = 20;
    public double omega0;

    // optional double omega_dot = 21;
    public double omegaDot;

    // optional double m_0 = 22;
    public double m0;

    // optional double delta_n = 23;
    public double deltaN;

    // optional double crc = 24;
    public double crc;

    // optional double crs = 25;
    public double crs;

    // optional double cuc = 26;
    public double cuc;

    // optional double cus = 27;
    public double cus;

    // optional double cic = 28;
    public double cic;

    // optional double cis = 29;
    public double cis;

    // optional double fit_interval = 30;
    public double fitInterval;

    public GalEphemerisProto() {
      clear();
    }

    public Ephemeris.GpsEphemerisProto getGpsEphemeris()
    {
      Ephemeris.GpsEphemerisProto newGpsEphemeris = new Ephemeris.GpsEphemerisProto();
      newGpsEphemeris.dataTime = null;
      newGpsEphemeris.prn = this.prn;
      newGpsEphemeris.week = this.week;
      newGpsEphemeris.svAccuracyM = this.svAccuracyM;
      newGpsEphemeris.svHealth = this.svHealth;
      newGpsEphemeris.iode = this.iode;
      newGpsEphemeris.iodc = this.iodc;
      newGpsEphemeris.toc = this.toc;
      newGpsEphemeris.toe = this.toe;
      newGpsEphemeris.tom = this.tom;
      newGpsEphemeris.af0 = this.af0;
      newGpsEphemeris.af1 = this.af1;
      newGpsEphemeris.af2 = this.af2;
      newGpsEphemeris.tgd = this.tgd;
      newGpsEphemeris.rootOfA = this.rootOfA;
      newGpsEphemeris.e = this.e;
      newGpsEphemeris.i0 = this.i0;
      newGpsEphemeris.iDot = this.iDot;
      newGpsEphemeris.omega = this.omega;
      newGpsEphemeris.omega0 = this.omega0;
      newGpsEphemeris.omegaDot = this.omegaDot;
      newGpsEphemeris.m0 = this.m0;
      newGpsEphemeris.deltaN = this.deltaN;
      newGpsEphemeris.crc = this.crc;
      newGpsEphemeris.crs = this.crs;
      newGpsEphemeris.cuc = this.cuc;
      newGpsEphemeris.cus = this.cus;
      newGpsEphemeris.cic = this.cic;
      newGpsEphemeris.cis = this.cis;
      newGpsEphemeris.fitInterval = this.fitInterval;

      return newGpsEphemeris;
    }

    public GalEphemerisProto clear() {
      dataTime = null;
      prn = 0;
      week = 0;
      svAccuracyM = 0D;
      svHealth = 0;
      iode = 0;
      iodc = 0;
      toc = 0D;
      toe = 0D;
      tom = 0D;
      af0 = 0D;
      af1 = 0D;
      af2 = 0D;
      tgd = 0D;
      rootOfA = 0D;
      e = 0D;
      i0 = 0D;
      iDot = 0D;
      omega = 0D;
      omega0 = 0D;
      omegaDot = 0D;
      m0 = 0D;
      deltaN = 0D;
      crc = 0D;
      crs = 0D;
      cuc = 0D;
      cus = 0D;
      cic = 0D;
      cis = 0D;
      fitInterval = 0D;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.dataTime != null) {
        output.writeMessage(1, this.dataTime);
      }
      if (this.prn != 0) {
        output.writeInt32(2, this.prn);
      }
      if (this.week != 0) {
        output.writeInt32(3, this.week);
      }
      if (java.lang.Double.doubleToLongBits(this.svAccuracyM)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(4, this.svAccuracyM);
      }
      if (this.svHealth != 0) {
        output.writeInt32(5, this.svHealth);
      }
      if (this.iode != 0) {
        output.writeInt32(6, this.iode);
      }
      if (this.iodc != 0) {
        output.writeInt32(7, this.iodc);
      }
      if (java.lang.Double.doubleToLongBits(this.toc)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(8, this.toc);
      }
      if (java.lang.Double.doubleToLongBits(this.toe)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(9, this.toe);
      }
      if (java.lang.Double.doubleToLongBits(this.tom)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(10, this.tom);
      }
      if (java.lang.Double.doubleToLongBits(this.af0)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(11, this.af0);
      }
      if (java.lang.Double.doubleToLongBits(this.af1)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(12, this.af1);
      }
      if (java.lang.Double.doubleToLongBits(this.af2)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(13, this.af2);
      }
      if (java.lang.Double.doubleToLongBits(this.tgd)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(14, this.tgd);
      }
      if (java.lang.Double.doubleToLongBits(this.rootOfA)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(15, this.rootOfA);
      }
      if (java.lang.Double.doubleToLongBits(this.e)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(16, this.e);
      }
      if (java.lang.Double.doubleToLongBits(this.i0)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(17, this.i0);
      }
      if (java.lang.Double.doubleToLongBits(this.iDot)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(18, this.iDot);
      }
      if (java.lang.Double.doubleToLongBits(this.omega)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(19, this.omega);
      }
      if (java.lang.Double.doubleToLongBits(this.omega0)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(20, this.omega0);
      }
      if (java.lang.Double.doubleToLongBits(this.omegaDot)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(21, this.omegaDot);
      }
      if (java.lang.Double.doubleToLongBits(this.m0)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(22, this.m0);
      }
      if (java.lang.Double.doubleToLongBits(this.deltaN)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(23, this.deltaN);
      }
      if (java.lang.Double.doubleToLongBits(this.crc)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(24, this.crc);
      }
      if (java.lang.Double.doubleToLongBits(this.crs)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(25, this.crs);
      }
      if (java.lang.Double.doubleToLongBits(this.cuc)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(26, this.cuc);
      }
      if (java.lang.Double.doubleToLongBits(this.cus)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(27, this.cus);
      }
      if (java.lang.Double.doubleToLongBits(this.cic)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(28, this.cic);
      }
      if (java.lang.Double.doubleToLongBits(this.cis)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(29, this.cis);
      }
      if (java.lang.Double.doubleToLongBits(this.fitInterval)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(30, this.fitInterval);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.dataTime != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.dataTime);
      }
      if (this.prn != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.prn);
      }
      if (this.week != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, this.week);
      }
      if (java.lang.Double.doubleToLongBits(this.svAccuracyM)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(4, this.svAccuracyM);
      }
      if (this.svHealth != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(5, this.svHealth);
      }
      if (this.iode != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(6, this.iode);
      }
      if (this.iodc != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(7, this.iodc);
      }
      if (java.lang.Double.doubleToLongBits(this.toc)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(8, this.toc);
      }
      if (java.lang.Double.doubleToLongBits(this.toe)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(9, this.toe);
      }
      if (java.lang.Double.doubleToLongBits(this.tom)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(10, this.tom);
      }
      if (java.lang.Double.doubleToLongBits(this.af0)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(11, this.af0);
      }
      if (java.lang.Double.doubleToLongBits(this.af1)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(12, this.af1);
      }
      if (java.lang.Double.doubleToLongBits(this.af2)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(13, this.af2);
      }
      if (java.lang.Double.doubleToLongBits(this.tgd)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(14, this.tgd);
      }
      if (java.lang.Double.doubleToLongBits(this.rootOfA)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(15, this.rootOfA);
      }
      if (java.lang.Double.doubleToLongBits(this.e)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(16, this.e);
      }
      if (java.lang.Double.doubleToLongBits(this.i0)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(17, this.i0);
      }
      if (java.lang.Double.doubleToLongBits(this.iDot)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(18, this.iDot);
      }
      if (java.lang.Double.doubleToLongBits(this.omega)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(19, this.omega);
      }
      if (java.lang.Double.doubleToLongBits(this.omega0)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(20, this.omega0);
      }
      if (java.lang.Double.doubleToLongBits(this.omegaDot)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(21, this.omegaDot);
      }
      if (java.lang.Double.doubleToLongBits(this.m0)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(22, this.m0);
      }
      if (java.lang.Double.doubleToLongBits(this.deltaN)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(23, this.deltaN);
      }
      if (java.lang.Double.doubleToLongBits(this.crc)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(24, this.crc);
      }
      if (java.lang.Double.doubleToLongBits(this.crs)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(25, this.crs);
      }
      if (java.lang.Double.doubleToLongBits(this.cuc)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(26, this.cuc);
      }
      if (java.lang.Double.doubleToLongBits(this.cus)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(27, this.cus);
      }
      if (java.lang.Double.doubleToLongBits(this.cic)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(28, this.cic);
      }
      if (java.lang.Double.doubleToLongBits(this.cis)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(29, this.cis);
      }
      if (java.lang.Double.doubleToLongBits(this.fitInterval)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(30, this.fitInterval);
      }
      return size;
    }

    @Override
    public GalEphemerisProto mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.dataTime == null) {
              this.dataTime = new android.location.cts.nano.GalileoEphemeris.GalTimeProto();
            }
            input.readMessage(this.dataTime);
            break;
          }
          case 16: {
            this.prn = input.readInt32();
            break;
          }
          case 24: {
            this.week = input.readInt32();
            break;
          }
          case 33: {
            this.svAccuracyM = input.readDouble();
            break;
          }
          case 40: {
            this.svHealth = input.readInt32();
            break;
          }
          case 48: {
            this.iode = input.readInt32();
            break;
          }
          case 56: {
            this.iodc = input.readInt32();
            break;
          }
          case 65: {
            this.toc = input.readDouble();
            break;
          }
          case 73: {
            this.toe = input.readDouble();
            break;
          }
          case 81: {
            this.tom = input.readDouble();
            break;
          }
          case 89: {
            this.af0 = input.readDouble();
            break;
          }
          case 97: {
            this.af1 = input.readDouble();
            break;
          }
          case 105: {
            this.af2 = input.readDouble();
            break;
          }
          case 113: {
            this.tgd = input.readDouble();
            break;
          }
          case 121: {
            this.rootOfA = input.readDouble();
            break;
          }
          case 129: {
            this.e = input.readDouble();
            break;
          }
          case 137: {
            this.i0 = input.readDouble();
            break;
          }
          case 145: {
            this.iDot = input.readDouble();
            break;
          }
          case 153: {
            this.omega = input.readDouble();
            break;
          }
          case 161: {
            this.omega0 = input.readDouble();
            break;
          }
          case 169: {
            this.omegaDot = input.readDouble();
            break;
          }
          case 177: {
            this.m0 = input.readDouble();
            break;
          }
          case 185: {
            this.deltaN = input.readDouble();
            break;
          }
          case 193: {
            this.crc = input.readDouble();
            break;
          }
          case 201: {
            this.crs = input.readDouble();
            break;
          }
          case 209: {
            this.cuc = input.readDouble();
            break;
          }
          case 217: {
            this.cus = input.readDouble();
            break;
          }
          case 225: {
            this.cic = input.readDouble();
            break;
          }
          case 233: {
            this.cis = input.readDouble();
            break;
          }
          case 241: {
            this.fitInterval = input.readDouble();
            break;
          }
        }
      }
    }

    public static GalEphemerisProto parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new GalEphemerisProto(), data);
    }

    public static GalEphemerisProto parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new GalEphemerisProto().mergeFrom(input);
    }
  }

  public static final class NeQuickModelProto extends
      com.google.protobuf.nano.MessageNano {

    private static volatile NeQuickModelProto[] _emptyArray;
    public static NeQuickModelProto[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new NeQuickModelProto[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .android.location.cts.GalTimeProto data_time = 1;
    public android.location.cts.nano.GalileoEphemeris.GalTimeProto dataTime;

    // repeated double alpha = 2;
    public double[] alpha;

    public NeQuickModelProto() {
      clear();
    }

    public NeQuickModelProto clear() {
      dataTime = null;
      alpha = com.google.protobuf.nano.WireFormatNano.EMPTY_DOUBLE_ARRAY;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.dataTime != null) {
        output.writeMessage(1, this.dataTime);
      }
      if (this.alpha != null && this.alpha.length > 0) {
        for (int i = 0; i < this.alpha.length; i++) {
          output.writeDouble(2, this.alpha[i]);
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.dataTime != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.dataTime);
      }
      if (this.alpha != null && this.alpha.length > 0) {
        int dataSize = 8 * this.alpha.length;
        size += dataSize;
        size += 1 * this.alpha.length;
      }
      return size;
    }

    @Override
    public NeQuickModelProto mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.dataTime == null) {
              this.dataTime = new android.location.cts.nano.GalileoEphemeris.GalTimeProto();
            }
            input.readMessage(this.dataTime);
            break;
          }
          case 17: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 17);
            int i = this.alpha == null ? 0 : this.alpha.length;
            double[] newArray = new double[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.alpha, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readDouble();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readDouble();
            this.alpha = newArray;
            break;
          }
          case 18: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            int arrayLength = length / 8;
            int i = this.alpha == null ? 0 : this.alpha.length;
            double[] newArray = new double[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.alpha, 0, newArray, 0, i);
            }
            for (; i < newArray.length; i++) {
              newArray[i] = input.readDouble();
            }
            this.alpha = newArray;
            input.popLimit(limit);
            break;
          }
        }
      }
    }

    public static NeQuickModelProto parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new NeQuickModelProto(), data);
    }

    public static NeQuickModelProto parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new NeQuickModelProto().mergeFrom(input);
    }
  }

  public static final class UtcModelProto extends
      com.google.protobuf.nano.MessageNano {

    private static volatile UtcModelProto[] _emptyArray;
    public static UtcModelProto[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new UtcModelProto[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional double a_0 = 1;
    public double a0;

    // optional double a_1 = 2;
    public double a1;

    // optional int64 tow = 3;
    public long tow;

    // optional int32 leap_seconds = 4;
    public int leapSeconds;

    public UtcModelProto() {
      clear();
    }

    public UtcModelProto clear() {
      a0 = 0D;
      a1 = 0D;
      tow = 0L;
      leapSeconds = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (java.lang.Double.doubleToLongBits(this.a0)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(1, this.a0);
      }
      if (java.lang.Double.doubleToLongBits(this.a1)
          != java.lang.Double.doubleToLongBits(0D)) {
        output.writeDouble(2, this.a1);
      }
      if (this.tow != 0L) {
        output.writeInt64(3, this.tow);
      }
      if (this.leapSeconds != 0) {
        output.writeInt32(4, this.leapSeconds);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (java.lang.Double.doubleToLongBits(this.a0)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(1, this.a0);
      }
      if (java.lang.Double.doubleToLongBits(this.a1)
          != java.lang.Double.doubleToLongBits(0D)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(2, this.a1);
      }
      if (this.tow != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(3, this.tow);
      }
      if (this.leapSeconds != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, this.leapSeconds);
      }
      return size;
    }

    @Override
    public UtcModelProto mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 9: {
            this.a0 = input.readDouble();
            break;
          }
          case 17: {
            this.a1 = input.readDouble();
            break;
          }
          case 24: {
            this.tow = input.readInt64();
            break;
          }
          case 32: {
            this.leapSeconds = input.readInt32();
            break;
          }
        }
      }
    }

    public static UtcModelProto parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new UtcModelProto(), data);
    }

    public static UtcModelProto parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new UtcModelProto().mergeFrom(input);
    }
  }

  public static final class GalNavMessageProto extends
      com.google.protobuf.nano.MessageNano {

    // enum RpcStatus
    public static final int UNKNOWN_RPC_STATUS = 0;
    public static final int SUCCESS = 1;
    public static final int SERVER_ERROR = 2;

    private static volatile GalNavMessageProto[] _emptyArray;
    public static GalNavMessageProto[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new GalNavMessageProto[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .android.location.cts.GalNavMessageProto.RpcStatus rpc_status = 1;
    public int rpcStatus;

    // optional .android.location.cts.NeQuickModelProto iono = 2;
    public android.location.cts.nano.GalileoEphemeris.NeQuickModelProto iono;

    // optional .android.location.cts.UtcModelProto utc_model = 3;
    public android.location.cts.nano.GalileoEphemeris.UtcModelProto utcModel;

    // repeated .android.location.cts.GalEphemerisProto ephemerids = 4;
    public android.location.cts.nano.GalileoEphemeris.GalEphemerisProto[] ephemerids;

    public GalNavMessageProto() {
      clear();
    }

    public GalNavMessageProto clear() {
      rpcStatus = android.location.cts.nano.GalileoEphemeris.GalNavMessageProto.UNKNOWN_RPC_STATUS;
      iono = null;
      utcModel = null;
      ephemerids = android.location.cts.nano.GalileoEphemeris.GalEphemerisProto.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.rpcStatus != android.location.cts.nano.GalileoEphemeris.GalNavMessageProto.UNKNOWN_RPC_STATUS) {
        output.writeInt32(1, this.rpcStatus);
      }
      if (this.iono != null) {
        output.writeMessage(2, this.iono);
      }
      if (this.utcModel != null) {
        output.writeMessage(3, this.utcModel);
      }
      if (this.ephemerids != null && this.ephemerids.length > 0) {
        for (int i = 0; i < this.ephemerids.length; i++) {
          android.location.cts.nano.GalileoEphemeris.GalEphemerisProto element = this.ephemerids[i];
          if (element != null) {
            output.writeMessage(4, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.rpcStatus != android.location.cts.nano.GalileoEphemeris.GalNavMessageProto.UNKNOWN_RPC_STATUS) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, this.rpcStatus);
      }
      if (this.iono != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.iono);
      }
      if (this.utcModel != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3, this.utcModel);
      }
      if (this.ephemerids != null && this.ephemerids.length > 0) {
        for (int i = 0; i < this.ephemerids.length; i++) {
          android.location.cts.nano.GalileoEphemeris.GalEphemerisProto element = this.ephemerids[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(4, element);
          }
        }
      }
      return size;
    }

    @Override
    public GalNavMessageProto mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            int value = input.readInt32();
            switch (value) {
              case android.location.cts.nano.GalileoEphemeris.GalNavMessageProto.UNKNOWN_RPC_STATUS:
              case android.location.cts.nano.GalileoEphemeris.GalNavMessageProto.SUCCESS:
              case android.location.cts.nano.GalileoEphemeris.GalNavMessageProto.SERVER_ERROR:
                this.rpcStatus = value;
                break;
            }
            break;
          }
          case 18: {
            if (this.iono == null) {
              this.iono = new android.location.cts.nano.GalileoEphemeris.NeQuickModelProto();
            }
            input.readMessage(this.iono);
            break;
          }
          case 26: {
            if (this.utcModel == null) {
              this.utcModel = new android.location.cts.nano.GalileoEphemeris.UtcModelProto();
            }
            input.readMessage(this.utcModel);
            break;
          }
          case 34: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 34);
            int i = this.ephemerids == null ? 0 : this.ephemerids.length;
            android.location.cts.nano.GalileoEphemeris.GalEphemerisProto[] newArray =
                new android.location.cts.nano.GalileoEphemeris.GalEphemerisProto[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.ephemerids, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new android.location.cts.nano.GalileoEphemeris.GalEphemerisProto();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new android.location.cts.nano.GalileoEphemeris.GalEphemerisProto();
            input.readMessage(newArray[i]);
            this.ephemerids = newArray;
            break;
          }
        }
      }
    }

    public static GalNavMessageProto parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new GalNavMessageProto(), data);
    }

    public static GalNavMessageProto parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new GalNavMessageProto().mergeFrom(input);
    }
  }
}
